import { Elysia } from "elysia";
import { AppContext } from "./core/AppContext";
import { registerRoutes } from "./core/Router";
import openapi from "@elysiajs/openapi";
import 'dotenv/config';

const app = new Elysia();
const ctx = new AppContext();
app.decorate("ctx", ctx);

// Initialize context services (SpotifyService etc.) before routes
await ctx.init();

// OpenAPI first so subsequent dynamic routes get documented
app.use(openapi({
	documentation: {
		info: {
			title: "Mega API",
			version: "1.0.50",
			description: "Mega API autogenerated documentation via @elysiajs/openapi"
		},
		servers: [
			{ url: "http://localhost:3000", description: "Local" }
		]
	}
}));

registerRoutes(app, ctx);

app.listen(3000);

ctx.logger.info(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)
