import { Elysia } from "elysia";
import { AppContext } from "./core/AppContext";
import { registerRoutes } from "./core/Router";
import openapi from "@elysiajs/openapi";

const app = new Elysia();
const ctx = new AppContext();

app.decorate("ctx", ctx);

// Register routes first so OpenAPI can pick them up after plugin initialization (plugin can be before too but keeping order explicit)
registerRoutes(app, ctx);

// OpenAPI / Scalar documentation setup
app.use(openapi({
	documentation: {
		info: {
			title: "Mega API",
			version: "1.0.50",
			description: "Mega API autogenerated documentation via @elysiajs/openapi"
		},
		servers: [
			{ url: "http://localhost:3000", description: "Local" }
		]
	}
}));

app.listen(3000);

ctx.logger.info(`🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`)
